version: "3.8"

services:
  app:
    container_name: app-backend
    image: app-backend
    restart: always
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    networks:
      backend: 
        aliases: 
          - rest   

networks:
  backend:
    external: true
    name: backend_network   